import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    scriptsSidebar: [
        {
            type: 'autogenerated',
            dirName: '.', // Generate sidebar from the docs folder (or versioned_docs/<version>)
        },
    ],
};

export default sidebars;
